### ISSUE TITLE
"Copy license text to clipboard" does not work on firefox

### ISSUE THREAD

**Issue by WhyNotHugo** [github/choosealicense.com#46]
When clickin the "Copy license text to clipboard", the license is not copied.
Running Firefox 22 on ArchLinux.

I'm constantly prompted to install a propietary plugin (#45), so that may be related.

**Comment by elcuervo** [comment]
I've sent #26 for that exact reason. It's not a "Copy to Clipboard" solution but a good alternative.

**Comment by haacked** [comment]
Yes, the copy license to clipboard requires Flash. @elcuervo I need to find time to code review #26 first. :)

**Comment by haacked** [comment]
Closing as we merged #26 already.

**Comment by WhyNotHugo** [comment]
On firefox 24, clicking "Copy license text to clipboard" still does nothing.

**Comment by haacked** [comment]
@hobarrera so the text of the license wasn't selected?

**Comment by XhmikosR** [comment]
@Haacked: the license text is copied fine, the text in the button isn't updated to reflect this like it does with Chrome.

**Comment by haacked** [comment]
@XhmikosR Ah! Thanks for the clarification. So this bug says that the text isn't copied. I'm going to keep this issue close and re-open #119.

**Comment by WhyNotHugo** [comment]
This issue is different, I have not installed the additional software required for the copy funcionality to work, so the "copy license" button should just select (but nothing at all is happening).

**Comment by WhyNotHugo** [comment]
On firefox 34.0.5, clicking the button still does not copy the license - it merely selects it (and the button does not update either). #232 won't fix the main issue here (the license it not being copied).

**Comment by XhmikosR** [comment]
Can you try the solution I suggest in that PR?

**Comment by XhmikosR** [comment]
Never mind, I tried it and both ways work.

**Comment by gjtorikian** [comment]
@hobarrera Can you show a GIF or video of your behavior? I'm on FF 35, OS X, and I can't reproduce:

![but](https://cloud.githubusercontent.com/assets/64050/5516117/322ae046-8840-11e4-9d6f-880ef747c877.gif)

**Comment by WhyNotHugo** [comment]
Behaviour has now changed, and I now get a dark grey overlay when hovering the mouse over the copy-license button:

![2015-03-14-090012_1920x1080_scrot](https://cloud.githubusercontent.com/assets/730811/6651613/a0943792-ca28-11e4-8136-65b1ea0b0d75.png)

It wouls seem that now, when hovering the button, an [object](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) tag is put inside of it, preventing me from clicking it. The browser (FIrefox in my case) shows a grey area since it doesn't know how to render this. Clicking it does nothing.

Some research revelas that an external plugin would be required to handle this, but it's not specified which one. It's also worth noting that many of the used attributes are obsolete on HTML5, meaning that this makes the document invalid, since it states: `<!DOCTYPE html>`.

**Comment by gjtorikian** [comment]
I'm on FF 37 and cannot reproduce that error.

As well, here's a list of current changes from  the last commit to fix this: https://github.com/github/choosealicense.com/compare/6a220e589a25c232125528f0c6ebe0e477777d20...gh-pages

Nothing touches the copy to clipboard code.

**Comment by WhyNotHugo** [comment]
@gjtorikian:

Can you retry on a clean setup? I'm amazed on how you can't reproduce the issue as time passed, but I've seen consistent (broken) behaviour on different machines and OSs.

**Comment by XhmikosR** [comment]
I can't reproduce either on any of my Windows 7/8.1 machines with Firefox 37 64-bit and the latest Flash player.
